log:
  level: -1
  enablejson: false

config:
  service-name: "login-backend"
  ginrouter: 
    router: "0.0.0.0:8085"
  auth:
    param:
      token-url: "http://localhost:8443/realms/my-realm/protocol/openid-connect/token?"
      client-id: "my-client"
      client-secret: "TbcVdCDnuu2krqgN8yv3tGdrACIfaWT0"